---
title: "explaratory analysis - no of visits"
output: html_document
date: "2022-09-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
#Loading necessary libraries

library(tidyverse)
library(modelr)
library(broom)

```

```{r}
#Getting the data set

data <- read.csv("Health data set.csv")
```

# Data glimpse

```{r}
glimpse(data)
```

```{r}
summary(data)
```

# Data transformation

```{r}
data2 <- data %>% 
    mutate(actualage = age*10,
           familyincome = faminc*10000)
data2          

```
```{r}

library(sjPlot)
view_df(data2, show.string.values = TRUE, show.values = TRUE, show.frq = TRUE, show.labels = TRUE, show.prc = TRUE)
```



```{r}

data2 %>% 
    select(ofp,ofnp,opp,opnp,hlth) %>% 
    filter(hlth == "poor") %>% 
    summarise(across(1:4,mean))

data2 %>% 
    select(ofp,ofnp,opp,opnp,hlth) %>% 
    filter(hlth == "excellent") %>% 
    summarise(across(1:4,mean))

```



# Distributions by gender
```{r}
data2 %>% 
    ggplot(aes(x = black)) + geom_bar(fill = "pink") +
    coord_flip()

data2 %>% 
    ggplot(aes(x = sex)) + geom_bar(fill = "pink") +
    coord_flip()

data2 %>% 
    ggplot(aes(x = privins)) + geom_bar(fill = "pink") +
    coord_flip()

data2 %>% 
    ggplot(aes(x = medicaid)) + geom_bar(fill = "pink") +
    coord_flip()

```

```{r}
data2 %>% 
    ggplot(aes(x = actualage)) + geom_bar(fill = "pink")
```

```{r}
data2 %>% 
    ggplot(aes(x = numchron)) + geom_bar(aes(fill = privins))


data2 %>% 
    ggplot(aes(x = numchron)) + geom_bar(aes(fill = hlth))

data2 %>% 
    ggplot(aes(x = ofp)) + geom_bar(aes(fill = hlth))
```
```{r}
data2 %>% 
    ggplot(aes(x = numchron, y = ofp, colour = hlth)) + geom_point() + facet_wrap(~sex)

data2 %>% 
    ggplot(aes(x = numchron, y = emr, colour = privins)) + geom_point() + facet_wrap(~black)


data2 %>% 
    ggplot(aes(x = numchron, y = emr, colour = privins)) + geom_point() + facet_wrap(~sex)
           
```
```{r}
data2 %>% 
    ggplot(aes(x = hlth, y= numchron, fill = privins)) + geom_boxplot()
```
```{r}
data2 %>% 
    ggplot(aes(x = emr)) + geom_bar(aes(fill = sex))
```

```{r}
data2 %>% 
    filter(black == "yes") %>% 
    ggplot(aes(x = actualincome)) + geom_histogram(bins = 100)
```

```{r}
data2 %>% 
    filter(black == "yes") %>% 
    ggplot(aes(x = familyincome, y = ofp, colour = hlth)) + geom_point() + facet_wrap(~region)
```

